version: '3.8'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./cdn.oaistatic.com/FUn368sO8Yo1nq60-uOqJ:/usr/share/nginx/html
      - ./default.conf:/etc/nginx/conf.d/default.conf

    restart: unless-stopped
